### ISSUE TITLE
Get data for multiple layers

### ISSUE THREAD

**Issue by danrr** [goabstract/abstract-sdk#100]
We are currently investigating using the Abstract SDK to extract values from the design files for use by developers, and we have reached a bottleneck with the current approach. Each value we want to extract is in a separate layer object, which requires a separate API call via `abstract.data.info`. We have hit rate limiting issues with only a few dozen items. Is there any way to batch data requests for multiple layers into one request?

**Comment by bitpshr** [comment]
Hi @danrr, thanks for reaching out.

Batching requests for specific layers is not yet supported, but we're currently working on internal caching improvements to both the SDK and the underlying CLI and API that should make the rate limit errors you encountered much less common. Until that work lands (or until we support true layer request batching, which may happen in the future), one option to bypass rate limiting is to use the SDK specifically with a CLI transport on a macOS machine.

By default, the SDK attempts to use Abstract severs over HTTP, which is rate limited. If you're able to run this script on a macOS machine with the Abstract desktop application installed, the SDK can instead be configured to use your local application and data instead, which is not rate limited:

```js
const abstract = new Abstract.Client({
  transportMode: "cli"
});
```

We realize this isn't ideal, as many CI scripts run on a server where it's not  possible to install the Abstract desktop application. We'll definitely prioritize both improving rate limits and investigating batch request support for layers and other commonly-retrieved entities.

Thanks again for putting this pain point on our radar, and don't hesitate to let us know if you have any additional questions.

**Comment by danrr** [comment]
Hi @bitpshr, thanks for getting back to me. 

When running the tool we wrote on top of the SDK locally, it works fine with the CLI. It's when we run the  Abstract SDK on CI, which doesn't let me easily install Abstract, that we've run into this. We've gotten around the issue by slowing down the calls made to SDK methods on our end so we never go over the 60 a minute (is that correct?) limit, and it work, even if a bit slow.
