### ISSUE TITLE
Intermittent errors when using the SDK

### ISSUE THREAD

**Issue by danrr** [goabstract/abstract-sdk#105]
I intermitently get `InternalServerError`s when requesting layer data using the SDK. Retrying the same request will, most of the time, return correct data. 

I realise this is an issue with the infrastructure behind it rather than the SDK itself, but the SDK is the entry point and I wasn't sure where else to raise this as an issue.

**Comment by tommoor** [comment]
Thanks @danrr – really appreciate you bringing this to our attention. Is there any particular method you're calling that is more likely to return internal errors in your experience?

**Comment by danrr** [comment]
@tommoor it's `abstract.data.info()` that's failing (that's what I meant by "requesting layer data", I should have been clearer)

**Comment by tommoor** [comment]
Thanks 👍 We've been tackling some scaling issues that it might be related to but we'll check in more detail on that endpoint

**Comment by bitpshr** [comment]
Thanks again for bringing this to our attention @danrr. We're investigating this more in the underlying API and CLI. If you encounter any additional errors, don't hesitate to open a new issue.
