### ISSUE TITLE
Access "role" via the user object

### ISSUE THREAD

**Issue by naughtandcross** [goabstract/abstract-sdk#108]
I'd love the ability to filter data by user role, i.e Admin vs Contributor vs Viewer. I can make some educated guess by analyzing each users Activity by type, but since we are already able to sort by these fields in app via the People tab, I figured I would inquire about the feasibility of getting this added to the API first. 😎

**Comment by tommoor** [comment]
Hey @naughtandcross – Abstract users are global so the role depends on the organization that is being queried, we do have the concept of memberships that includes this information though.

@bitpshr it WOULD be nice if we were able to provide a way to access the role without having to manually join memberships data on the clientside. Any thoughts on what an interface for that could look like?

**Comment by bitpshr** [comment]
Hi @naughtandcross, thanks for taking the time to file this feature request. As of `abstract-sdk@1.2.0`, you can now access [memberships](https://sdk.goabstract.com/docs/abstract-api/#memberships) that are specific to a project or an organization. These membership objects contain a `role`, the `User` that the membership represents, and other useful information.

Please review this new functionality and don't hesitate to let us know if you any issues, questions, or feedback.
