### ISSUE TITLE
Enable CORS for API endpoints

### ISSUE THREAD

**Issue by bitpshr** [goabstract/abstract-sdk#110]
While the SDK will work in both a browser and a node context from a JavaScript perspective, the backing API that the SDK uses by default at https://api.goabstract.com still has CORS enabled and can't be accessed by external domains at this time.

We should enable CORS for SDK-supported endpoints and document any necessary configuration.

**Comment by tommoor** [comment]
Great news, we've now opened up CORS on the API to any domain. Happy hacking!
