### ISSUE TITLE
Improve documentation of projects endpoints

### ISSUE THREAD

**Issue by tommoor** [goabstract/abstract-sdk#121]
- [ ] projects.info is not documented
- [ ] projects.list does not include the options that may be passed

https://spectrum.chat/abstract/developers/is-there-a-way-to-get-a-list-of-just-active-projects~af00c66a-c415-4332-961e-f0c0ab660dfc

**Comment by bitpshr** [comment]
Fixed by https://github.com/goabstract/abstract-sdk/pull/124.
