### ISSUE TITLE
Add file export to CLI transport

### ISSUE THREAD

**Issue by Zahlii** [goabstract/abstract-sdk#125]
Hi Everyone,

Sadly the issue under https://github.com/goabstract/abstract-sdk/issues/73 was closed without any notice or updates in the meantime. We are still waiting for some way to extract the raw sketch files from Abstract via the API. Is there any roadmap/plan to allow this in the future? Is there any way I could support in getting this feature done?

**Comment by bitpshr** [comment]
Hi @Zahlii, thanks for taking the time to reopen this issue and to put it back on our radar. This is something that we're actively investigating and hope to include in a future release. Please feel free to subscribe to this issue as a means of knowing when this functionality lands; we'll definitely keep this thread updated going forward.

**Comment by bitpshr** [comment]
Hi @Zahlii. We added support for exporting Sketch files using an SDK client that's configured to use the [CLI transport](https://sdk.goabstract.com/docs/transports/#cli) as of `abstract-sdk@v1.5.0`. This functionality is available via the new [`files.raw`](https://sdk.goabstract.com/docs/abstract-api/#retrieve-an-sketch-file) method. We're still investigating the feasibility of exporting Sketch files using Abstract's HTTP API, but please let us know if you have any issues while testing this CLI-based implementation.

**Comment by bitpshr** [comment]
Closing this issue since this functionality now exists in the CLI transport since e5d31f94111482eb2cd57ffcade6aa56c2f549b1. We're still investigating the feasibility of exporting Sketch files using Abstract's HTTP API, and plan to open a new issue to track that functionality in the future.
