### ISSUE TITLE
Provide Typescript definition files

### ISSUE THREAD

**Issue by emilwidlund** [goabstract/abstract-sdk#140]
Would be great if we could get Typescript definitions for this SDK. Could we do this by converting the flow-types into Typescript definitions with an appropriate tool somehow?

**Comment by bitpshr** [comment]
Hi @emilwidlund, thanks for reaching out. We're working to provide TypeScript definition files as part of our next minor release and will update this ticket accordingly.

**Comment by emilwidlund** [comment]
> Hi @emilwidlund, thanks for reaching out. We're working to provide TypeScript definition files as part of our next minor release and will update this ticket accordingly.

Perfect, thanks!

**Comment by bitpshr** [comment]
Closed with https://github.com/goabstract/abstract-sdk/pull/148.
