### ISSUE TITLE
EndPointUndefinedError in CLI transport mode

### ISSUE THREAD

**Issue by meyermeyer** [goabstract/abstract-sdk#153]
I've been using the API and keep bumping up against rate limits so I tried switching to transportMode: 'cli' and I get this error:
EndpointUndefinedError: Endpoint "projects.list" not defined in "cli" transport.

The endpoint exists in API transport mode.  Any thoughts why that might be happening?

**Comment by tommoor** [comment]
Hi @meyermeyer – the `projects.list` endpoint is not available via the CLI transport - this transport is mainly for querying data this is available on your local disk, such as files, artboards etc whereas projects only exist via the API.

In the docs we annotate which transports can be used with a badge,

![image](https://user-images.githubusercontent.com/380914/62254634-c8706000-b3ae-11e9-89de-07724bebf446.png)

Hope this helps!

**Comment by meyermeyer** [comment]
gotcha, yes that is helpful. thanks!
