### ISSUE TITLE
Feedback on Abstract SDK from web developer

### ISSUE THREAD

**Issue by berezovskycom** [goabstract/abstract-sdk#174]
Hey to all Abstract team.
Firstly, thanks for building Abstract SDK, I believe it's very cool for the design and development community. As I was playing with your SDK for some time, I have noticed things that can be improved:
- It's not really understandable in what environment the SDK shall be used. If it runs in node.js, it uses experimental features, which does not have a lot of support around devs. In my case, I had to update to a newer version of node.
- Some kind of starters boilerplate would really save up my time, for example, a boilerplate for developing Sketch plugins. Currently, skpm (Sketch Plugin Manager) does not support async/await requests, so instead of diving in creating the plugin, I had to google how to make async requests in skpm.
- Also, a good example would be Next.js documentation, which has the 'learn' section, where you complete tutorials, download files if needed, and even answer question after every tutorial step https://nextjs.org/learn/basics/getting-started
- In API reference in examples it's not obvious what the object 'abstract' means. I had to look up by myself and found out that abstract = my current client constant (await new Abstract.Client({})). It would be helpful if there would be a reference what abstract meant to be.
Feel free to ping me if you need to chat more about those points. I hope, my feedback will help.
-Vladimir from Flawless App team

**Comment by bitpshr** [comment]
Hi @berezovskycom, thank you for taking the time to provide such thorough and actionable feedback! Everything you mentioned is totally valid, and we plan to address most of these items over the next few weeks. Some of these items are quick wins, like making our documentation better and clearly specifying minimum versions of Node.js. Other items listed are a bit more involved, like adding better boilerplate code and a tutorial system, and we're actively planning a documentation overhaul scheduled to start soon after the holidays. Our newly-planned site should address all of these concerns.

I'll definitely leave this issue open to track the documentation improvements that you suggested around `abstract` and Node.js versions. Thanks again for helping us make our SDK and its documentation as clear and reliable as possible, this is very helpful.

**Comment by berezovskycom** [comment]
Hi @bitpshr!
Thanks for your reply. I took some time to think about your feedback.
So, yes, specifying the minimum Node.js version would've prevented my case. It's great that you can fix it fast. Perfect choice on Docusaurus, used to work with it before, really dev-friendly. You might want to contact [Docusaurus](https://github.com/facebook/docusaurus/edit/master/website-1.x/data/users.js) to add Abstract as [users](https://docusaurus.io/en/users) for better brand recognition.

Tutorial system with boilerplate would be a killer feature. Definitely look forword on looking at it later. Great idea.

Besides, I just noticed that it would be nice to add a 'copy' button for every embedded code, most docs have such thing. And you might want to change the domain, since your main website is abstract.com (not goabstract anymore). I suggest you to create redirects, so people with the outdated urls would still visit your website.

I do believe that Abstract is moving fast, so good luck on your implementation!
Vladimir.

**Comment by bitpshr** [comment]
Minimum Node version updated in 5b55194aafe9707365b8d9cb6319e2a9fcbadb91 and 487b9f9f83f423431d4eda145629755969d72d3c. Thanks again for such great feedback @berezovskycom; we've taken everything you've listed above we're using it to help inform the new documentation system that's currently being planned. Don't hesitate to reach back out if you have any additional thoughts.
