### ISSUE TITLE
startSha / endSha do not work when loading commits.list

### ISSUE THREAD

**Issue by tommoor** [goabstract/abstract-sdk#175]
The SDK expects `startSHA` / `endSHA` and passes that to the API request, however the server expects `startSha` / `endSha` as the parameter names.

https://github.com/goabstract/projects/blob/master/stable/api/app/controllers/commits_controller.rb#L23-L24

**Comment by bitpshr** [comment]
Fixed with 457c0a78b548d44c43c370cd32f7ddf1f60754c5.
