### ISSUE TITLE
Full Project CRUD?

### ISSUE THREAD

**Issue by benmcginnis** [goabstract/abstract-sdk#180]
Hi folks, I'm looking to automate some manual work that goes into new projects for our team and a lot of it is going to depend on being able to create / update Abstract projects via your API.  Any ETA on when you could add a create endpoint here? Would a pull request be appreciated?

https://github.com/goabstract/abstract-sdk/blob/a21c7af3f75d459ef196fe6729b1a7c0d63a441a/src/endpoints/Projects.js#L16

**Comment by tommoor** [comment]
Hey @benmcginnis – totally understand the need for this. Unfortunately a PR here won't do much good as the issue is a lack of support on our API for creating projects right now, there is a dependency on the desktop client that we need to resolve first.

**Comment by benmcginnis** [comment]
Thanks for letting me know @tommoor.  Any thoughts on priority?  I'm specing out a full workflow through QA automation that would depend on this to work.

**Comment by tommoor** [comment]
We're working on enabling project creation on the web which will be dependent on the same endpoint – I'm not directly involved in the work so can't give an estimate, other than to say the project is ongoing.

**Comment by benmcginnis** [comment]
Thank you!

**Comment by bitpshr** [comment]
Thanks for helping us prioritize this feature internally @benmcginnis. Don't hesitate to reach out with any additional questions or feature requests.

**Comment by benmcginnis** [comment]
Thanks, happy to help!

**Comment by MichaelZaporozhets** [comment]
this would be awesome. +1

**Comment by bitpshr** [comment]
Addressed as part of #201.
