### ISSUE TITLE
Documentation for changesets is incorrect

### ISSUE THREAD

**Issue by tommoor** [goabstract/abstract-sdk#181]
https://sdk.goabstract.com/docs/reference/#retrieve-a-changeset

It should be possible to also load a changeset with a branch descriptor. Also `CommitDescriptor` here should be `BranchCommitDescriptor` as a `branchId` is required.

**Comment by tommoor** [comment]
After looking further the `info` endpoint doesn't even exist! It's either `commit` or `branch` – I'm not sure why we chose to split this one up, can it not be `info` like the rest?

**Comment by bitpshr** [comment]
The documentation is definitely dated here. If we go with one endpoint that returns multiple types, consumers will have to check properties on the returned value to refine the type to appease the Flow compiler.

**Comment by bitpshr** [comment]
After looking into this further, we did update the documentation when we landed `changesets.branch` and `changesets.commit`. This is live at https://developer.abstract.com/docs/abstract-api/#changesets. It looks like developer.abstract.com and sdk.goabstract.com are out of sync for some reason.

**Comment by bitpshr** [comment]
The URL posted in the original issue description is invalid (note the outdated `/reference` URL path.) Closing since the documentation is correct, but will add a redirect from `/docs/reference` to `docs/abstract-api` since Fastly is caching this (and Google is apparently still indexing it as well.)
