### ISSUE TITLE
API Transport files.raw endpoint

### ISSUE THREAD

**Issue by MichaelZaporozhets** [goabstract/abstract-sdk#182]
Is there any reason the `files.raw` endpoint is not available for the http api?

**Comment by bitpshr** [comment]
Hi @MichaelZaporozhets, thanks for reaching out. To date, file export functionality only existed in Abstract's CLI and didn't exist in the API at all. We're actively working on (and almost done!) adding this functionality to the API, and we hope to land this endpoint in the SDK within the next few weeks.

**Comment by MichaelZaporozhets** [comment]
> Hi @MichaelZaporozhets, thanks for reaching out. To date, file export functionality only existed in Abstract's CLI and didn't exist in the API at all. We're actively working on (and almost done!) adding this functionality to the API, and we hope to land this endpoint in the SDK within the next few weeks.

Ah- I see! Glad to hear it's being worked on- i'd be very willing to help out once it's ready in API 🙂

It might be outside the scope of this repository, but a separate API doc might be useful to enable more community engagement.

**Comment by weyert** [comment]
Happy to hear that! Looking forward to this feature :D

**Comment by tommoor** [comment]
> a separate API doc might be useful to enable more community engagement.

Could you say more about what you mean here?

**Comment by MichaelZaporozhets** [comment]
@tommoor Given that the web api development track is internal and is/can be developed asynchronously to the sdk- creating a spec portal for the web api would allow external developers to develop/contribute to the sdk against that spec/contract, rather than leaving pressure of feature sync on the team that maintains the sdk and/or api. 

Lots of assumptions here and slashes to match but I'm hoping it's clear 🙂

**Comment by weyert** [comment]
I would love to know what the timings are to support downloading Sketch files from Abstract via the API? As it's hard to convince people to run a Mac server just to be able to generate design tokens from a Sketch file via our CI environment.

**Comment by bitpshr** [comment]
Hi @weyert. This functionality will be part of the upcoming `abstract-sdk@8.0.0` major release, which should be live by the end of the week. We'll be sure to comment on this issue when that happens to let you know when it's available for use.

**Comment by bitpshr** [comment]
API file export is now live in the latest `abstract-sdk@8.0.0-beta.7` prerelease and will be included in the upcoming `abstract-sdk@8.0.0` major release.
