### ISSUE TITLE
Files endpoint does not return libraries

### ISSUE THREAD

**Issue by naughtandcross** [goabstract/abstract-sdk#190]
There is currently no way of discerning which Libraries have been linked to each Project via the API, and the process of checking these connections manually is quite tedious.

Having the ability to obtain the array of Libraries (returning File object references) within the Project object would be super helpful here.

**Comment by tommoor** [comment]
Thanks for the request, this does look like it's an oversight.

**Comment by tommoor** [comment]
@bitpshr this is similar to https://github.com/goabstract/abstract-sdk/pull/184 and is also an internal blocker for similar reasons. We're dropping the `libraries` key of the API response and only returning `files` – we should introduce a `FilesResponse` concept for the files#list endpoint.

**Comment by bitpshr** [comment]
Feature live as of https://github.com/goabstract/abstract-sdk/pull/194.
