### ISSUE TITLE
Strategy for policies

### ISSUE THREAD

**Issue by tommoor** [goabstract/abstract-sdk#192]
Many API endpoints return a `policies` key alongside the `data` key – this is used for knowing the authorization of the current token as it pertains to the objects in the response.

As we continue to use the SDK internally we need access to the policies alongside the data, this could simply be returned as part of the response envelope or treated differently, I'm open to ideas.

**Comment by amccloud** [comment]
It would be nice to avoid exposing the envelope concepts pulically.

If this was cached internally so that subsequent calls to policies (or really any normalized data) can be tracked

```
const params = { projectId: '1' };
const policies = await abstract.policies.show(params); // load policies

// or

const project = await abstract.projects.show(params); // load project and...
const policies = await abstract.policies.show(params); // ...then use cache to access related data
```

**Comment by tommoor** [comment]
@amccloud I think the only issue with this solution, apart from any complexity introduced, is that there are different endpoints that would have identical `params`. Eg, a list of projects might only take the `organizationId` param, but also a single organization query would have the same.

Rather than exposing the envelope itself would you be opposed to the `policies` key being returned by the SDK at the same level as the data, eg it might look like:

```
{
  users: [...],
  branches: [...],
  policies: [...]
}
```

**Comment by bitpshr** [comment]
I think that mixing `policies` with actual data feels a little odd. It may be radical, but I think that we should pass through each API response as-is without any normalization, since this is the same data that consumers would receive if they hit our API directly via HTTP requests (which may happen in the future, and can already be done today.) The idea of using the SDK to hide "internal" data is nice in theory, but it's definitely complicated internal ([and external](https://github.com/goabstract/abstract-sdk/issues/190)) adoption.

**Comment by amccloud** [comment]
@tommoor good point I had that feeling as I typed it though I thought it might not actually be the case. Do we return a list of policies for list? I would expect a org descriptor to always return policies for org to avoid the ambiguity 

I agree with @bitpshr mixing the two and creating yet another type of data here would not be ideal. Maybe we can expose the generic parts of the envelope (no relations) as `Envelope<Project>` which can include policies and other common properties  

Also just throwing this out, what if we provided a `onResponse` callback option to the client?  Could we implement that in ui and normalize all responses straight to redux. You could just use policy selectors as necessary

**Comment by tommoor** [comment]
> Also just throwing this out, what if we provided a onResponse callback option to the client?

Not a huge fan of this just because it would make usage of the SDK within the existing request framework kind of confusing (which has been going quite nicely all-in-all).

> Maybe we can expose the generic parts of the envelope (no relations) as `Envelope<Project>` which can include policies

I'm not fully following this, example?

**Comment by amccloud** [comment]
> Not a huge fan of this just because it would make usage of the SDK within the existing request framework kind of confusing (which has been going quite nicely all-in-all).

Would it only impact the loading for related entities, which are mostly opaque to the request framework; outside of where they get loaded in `onSuccess` and `normalize`?

e.g. If I request a project I would not expect the request framework to track request for the related entities like policies (though that would be cool!)

> I'm not fully following this, example?

Would like to avoid view details to leaking into the public api. Data returned in the envelope can often be tied to view/specific optimizations and not necessarily for general api usage

```js
type Envelope<T> = {|
  ...T,
  entities: { // NOTE: `entities` would be a reserved property name
	[entity: ?string]: {
      // Would be nice if it was keyed by id for useful lookups
      [entityId: string]: mixed
    }
    // policies: {...},
    // users: {...},
    // branches: {...},
  }
|};

const files = await abstract.files.list(project); // where list(): Envelope<File[]>

console.log(Object.keys(files.entities.libraries).length);

// or

dispatch(entitiesReceived(files.entities));
console.log(getLibraryCountForProject(getState(), project));
```

**Comment by tommoor** [comment]
The `entityId` is specific to our frontend implementation though, the database `uuid` can't be used for this – to have this work the backend would need to start constructing those unique id's which would be a lot of extra work and kind of weird from an API consumption pov.

I'm understanding your `onResponse` idea a bit better now, could be neat but it would probably but it might be a bit magical for future folks trying to figure out how it all works – are you thinking that `onResponse` could just handle policies, for example, which are in the same envelope key always?

We really need to come to a decision on this before EOW btw, it's blocking further frontend work on partial sync.

**Comment by amccloud** [comment]
> The entityId is specific to our frontend implementation though, the database uuid can't be used for this – to have this work with our existing entitiesReceived action the backend would need to start constructing those unique id's which would be a lot of extra work and kind of weird from an API consumption pov.

That part is not important, can also be an array like you suggested. They key part here is that `entities` is the only public api

Everything after entities, the names of related entites and how they are keyed, objects or arrays can be considered implementation details until we expose the proper api for accessing those related entities

> We really need to come to a decision on this before EOW btw, it's blocking further frontend work on partial sync.

Under a deadline like that we should be aiming to expose the minimum to unblock this. Instead of `entities` we could also maybe just tack on or expose the original response. That way we can pass it to our exisiting normalization scheme

```js
const files = await abstract.files.list(project, { 
  onResponse: response => dispatch(normalizeFiles(response))
});
```

This might actually work out better than the global `onResponse` callback because we can map `files.list` to the correct schema

**Comment by kvnsmth** [comment]
@amccloud I really like the idea of exposing a simple way to access the original response. That keeps the API clean for most consumers, but gives extra flexibility if you need it.

**Comment by tommoor** [comment]
@kvnsmth we had a quick discussion call and decided that for now we'll provide a way to access the original raw response, but it'll be available in a "hidden" manner on the object returned from the promise rather than a separate callback.

The callback approach is kind of incompatible with the way our internal request framework is structured.

**Comment by kvnsmth** [comment]
@tommoor sounds good!

**Comment by tommoor** [comment]
Considering this resolved with the `unwrap` work above ^
