### ISSUE TITLE
Is there a way to update the visibility of the project through the SDK?

### ISSUE THREAD

**Issue by chadmalla-ff** [goabstract/abstract-sdk#195]
I am running a script that will get me a list of the projects that have their `visibility` set to `organization`. I then want to set it to `specific`. I don't see an `update` functionality for this property, is it at all possible to achieve this through a script?

**Comment by bitpshr** [comment]
Hi @chadmalla-ff, thanks for reaching out. Updating projects is not currently supported via the SDK, but we're actively working on adding support for full project CRUD operations. We've increased the priority on this and hope to include it in the upcoming `abstract@8.0.0` major release.

Thanks for raising this feature; stay tuned to this issue for updates as to when this lands.

**Comment by chadmalla-ff** [comment]
Thank you @bitpshr , looking forward to this!

**Comment by bitpshr** [comment]
Addressed as part of #201.
