### ISSUE TITLE
Document and type LayerProperties object

### ISSUE THREAD

**Issue by tommoor** [goabstract/abstract-sdk#205]
This is one of the most-used endpoints in our SDK for getting really valuable information out of sketch files such as colors, properties etc. But we don't document or type what's available here – seems like relatively low hanging fruit.

**Comment by berezovskycom** [comment]
Hey Tom!
Yes, totally agree with that.
All the LayerProperties which are used in sdk are added and will be available for public view when the new documentation arrives.
However, we lack LayerProperties description (e.g. what is LayerFillNoiseTypeWhite, where LayerFill might be useful, etc.). Will add the task to backlog.
100% it would be useful for devs who want to make their plugins using Abstract
