### ISSUE TITLE
SDK embed generator not working

### ISSUE THREAD

**Issue by mkeys** [goabstract/abstract-sdk#212]
The embed generator on the [SDK site](https://sdk.abstract.com/docs/embed/) isn't working. I get the error "Invalid share link. Please try again..."

Here is the PSL link I tried: https://share.goabstract.com/aaec8bba-f473-4f64-96e7-bff41c70ff8a?mode=design&sha=576401cfbcc90bdde3a2a16500c1f4e74dd02c80

**Comment by tommoor** [comment]
Thanks @mkeys !

Sidenote: It'd be nice if we ensured the generated embeds have the new domain

**Comment by bitpshr** [comment]
The embed generator at https://developer.abstract.com/docs/embed/#generating-an-embed should now handle the above URL properly. Thanks for filing this issue @mkeys!
