### ISSUE TITLE
Add endpoint to list files at a commit

### ISSUE THREAD

**Issue by ajschwieterman** [goabstract/abstract-sdk#234]
I'm trying to get a list of all files that are in a specific branch and commit ID (see request below), but the HTTPs response states it is a forbidden request.

https://api.goabstract.com/projects/{project_id}/branches/{branch_id}/commits/{commit_id}/files

**Comment by tommoor** [comment]
We can't really debug based on this information – could you post the code you're using?

**Comment by ajschwieterman** [comment]
I'm sending a GET HTTPS request via Postman with the following URL and adding my API token in the request header:
https://api.goabstract.com/projects/{project_id}/branches/{branch_id}/commits/{commit_id}/files

project_id = the id of the project I am accessing
branch_id = the branch of the project I'm accessing, in this case "master"
commit_id = the version of "master" I am trying to access
I get a 403 response error.

![Screen Shot 2020-03-18 at 13 27 36](https://user-images.githubusercontent.com/50152740/76990379-43768e80-691e-11ea-9c3d-514e539e062a.png)

If I send the below HTTPS request, I get a list of files in the latest version of the branch.
https://api.goabstract.com/projects/{project_id}/branches/{branch_id}/files

![Screen Shot 2020-03-18 at 13 32 50](https://user-images.githubusercontent.com/50152740/76990407-4c676000-691e-11ea-8de1-7fdf9199217f.png)

But if I try to add the specific commit I'm looking to see, I'll get the 403 error.

Here is a HTTPS request of the commits for the branch.

![Screen Shot 2020-03-18 at 13 33 24](https://user-images.githubusercontent.com/50152740/76990504-6dc84c00-691e-11ea-99dc-2a8f93f03a3e.png)

**Comment by tommoor** [comment]
This endpoint doesn't yet exist, did you see it documented somewhere?

You can find a list of files that were _changed_ at a commit though using `/changeset` instead of `/files`

**Comment by ajschwieterman** [comment]
This document shows it is possible through the SDK.  Is this not the same?
https://sdk.goabstract.com/docs/abstract-api/#list-all-files

**Comment by tommoor** [comment]
The example in the SDK is the same as the first response you showed, which succeeds but I'd agree that the inclusion of `sha` in the parameters makes it look possible.

I think this is useful and not a heavy lift on our side so I'll file an internal issue to add support for the endpoint.

**Comment by ajschwieterman** [comment]
Can you also add endpoints to list layers at a commit?

![Screen Shot 2020-03-18 at 14 19 22](https://user-images.githubusercontent.com/50152740/76993726-b0d8ee00-6923-11ea-936d-4fd399e2ebfc.png)

**Comment by konstantinn** [comment]
@tommoor @ajschwieterman 
`/projects/:project_id/branches/:branch_id/commits/:commit_id/files` endpoint was released today

**Comment by berezovskycom** [comment]
Adding to SDK
https://github.com/goabstract/abstract-sdk/pull/275
