### ISSUE TITLE
8.0.0-beta.20 throws error on performance

### ISSUE THREAD

**Issue by iJigg** [goabstract/abstract-sdk#243]
api: ReferenceError: performance is not defined
      at makeRequest (project/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:79:25)

node v12.15.0

**Comment by tommoor** [comment]
Thanks for letting us know, you can safely use pre release 19 in the meantime

**Comment by berezovskycom** [comment]
I was running node and the issue still appeared. The user can’t even authenticate. Still says “performance is not defined”. Node v12.16.1

**Comment by tommoor** [comment]
And you're not passing an analyticsCallback ?

**Comment by rickharris** [comment]
Confirmed. I'll get it fixed up.
