### ISSUE TITLE
Update to the latest core-js version?

### ISSUE THREAD

**Issue by mascardoso** [goabstract/abstract-sdk#261]
I keep getting this on your latest with a fresh install.
`Error: Cannot find module 'core-js/modules/web.dom.iterable'`

Even if I try adding `core/js - 3` (latest) I keep having the same issue.

Fallback to `core/js - 2` works, so I'm pretty sure you're still using / targetting it.

Thanks.

**Comment by berezovskycom** [comment]
Hi @mascardoso! Thank you for helping us, could you please check this pr and see if your issue has been resolved?
https://github.com/goabstract/abstract-sdk/pull/265

**Comment by mascardoso** [comment]
Hi.
Apologies on the delay @berezovskycom 
It works.

**Comment by berezovskycom** [comment]
Merged to master. Thanks @mascardoso!
