### ISSUE TITLE
Sample project?

### ISSUE THREAD

**Issue by gegagome** [goabstract/abstract-sdk#268]
Hi there

Can you please provide a sample project for developers who can't figure out where to apply the code? Including the token.

I have developed plugins for Sketch but don't see where in Abstract app or what type of package the API is used.

Thanks

**Comment by Geek-1001** [comment]
Hello! Thanks for the heads up on this one. 

There is a number of open-source plugins/extensions developed with Abstract SDK that can help you understand the concepts better:

- [abstract-fetch-assets](https://github.com/Zeukkari/abstract-fetch-assets) – simple extensions to extract assets from Abstract. In this project authorization token is stored in .env file (it's not recommended to push/commit token into GitHub repo, just replace it on your local machine as described in Setup section)
- [abstract-link-loader](https://github.com/goabstract/abstract-link-loader) – another option is to start webpack with `ABSTRACT_TOKEN` defined in the environment as described in README.

We're currently working on improving the [Abstract SDK Website](https://sdk.abstract.com), please stay tuned for more updates on that.

Hope this is helpful!
