### ISSUE TITLE
abstract-cli could not be accessed at the expected path

### ISSUE THREAD

**Issue by xdrdak** [goabstract/abstract-sdk#276]
When attempting to use `abstract-sdk@8.0.0-beta.30`, an error is thrown on client instantiation:

```
abstract-cli could not be accessed at the expected path [...]
```

This bug is reproducible under the following environment:

**OS**: macOS Catalina Version 10.15.4
**Node**: v14.0.0

---

Additional Details:

Bug cannot be reproduced on `node v12.17.0 lts` or `node v10.16.0`

**Comment by slmosl** [comment]
Going over the `resolveCLIBinary` code in abstract-cli/index.js , it looks like there is a type mismatch when using `accessSync`

The way it is used right now in the code is `fs.accessSync(binPath, "rx");`
while the correct way to use it is `fs.accessSync(binPath, fs.constants.R_OK | fs.constants.X_OK)`

see: https://nodejs.org/api/fs.html#fs_fs_accesssync_path_mode

**Comment by berezovskycom** [comment]
Hi @xdrdak @slmosl we'll make a release of abstract-cli asap.
