### ISSUE TITLE
Do not throw MultiError unless necessary

### ISSUE THREAD

**Issue by amccloud** [goabstract/abstract-sdk#279]
The sdk is configured to throw MultiError [if the number of caught errors matches the number of transports configured](https://github.com/goabstract/abstract-sdk/blob/master/src/endpoints/Endpoint.js#L93). This means 1 transport with 1 error will throw a MultiError. This behavior is confusing as MultiError implies multiples errors or the possibility for multiple errors

The unecessary MultiError makes the test suite almost unworkable as any expected exceptions are masked

<img width="1451" alt="Screenshot 2020-06-04 15 32 34" src="https://user-images.githubusercontent.com/38463/83817289-3180ce00-a679-11ea-94e4-f15ff1fa5c7e.png">

vs

<img width="1419" alt="Screenshot 2020-06-04 15 38 55" src="https://user-images.githubusercontent.com/38463/83817398-815f9500-a679-11ea-97cf-1819d2fb2b59.png">

I took a quick pass at fixing this but the behavior around MultiError almost always throwing is ingrained in more than a few test that I can update right now. I created this ticket In the interest of getting this fixed as I think it greatly affects someone's ability to contribute to our test and the sdk overall

cc: @berezovskycom as I know you also ran into this when you worked with test

**Comment by berezovskycom** [comment]
@amccloud 100%
Will add the task to next sprint
