### ISSUE TITLE
How to perform a commit using SDK?

### ISSUE THREAD

**Issue by Koshub** [goabstract/abstract-sdk#307]
Hello

Thank you for sharing the API and SDK for it. 

As a part of CI automation of a product design system and design token management I would like to fetch a sketch file from Abstract source control (which is a sketch library) to CI server, update it and commit the changes back to Abstract source control. Is that possible using Abstract SDK? It seems I could not find this API in docs but this is actually the most important part to have a write access to the Abstract source control.

Best regards

**Comment by tommoor** [comment]
Hi @Koshub – we don't offer the ability to commit into Abstract at this time I'm afraid. There is not currently a timeline for doing so.

**Comment by Koshub** [comment]
@tommoor Thank you for reply
