### ISSUE TITLE
Missing `invariant` dependency

### ISSUE THREAD

**Issue by timhudson** [goabstract/abstract-sdk#316]
In https://github.com/goabstract/abstract-sdk/pull/309, the `invariant` module was imported into `src/endpoints/Branches.js`. Unfortunately, this is not declared as a dependency within `package.json`.

https://github.com/goabstract/abstract-sdk/blob/7ffcc9a54aea5d0b1c536674f2e16cca3b1f9770/src/endpoints/Branches.js#L2

This breaks usage of `abstract-sdk` unless `invariant` happens to be included as a transitive dependency of another installed package.

**Comment by tommoor** [comment]
Addressed in v8.1.0, thanks for filing.
