### ISSUE TITLE
Exporting a file using public API abstract.files.raw fails with BadRequest

### ISSUE THREAD

**Issue by dkamburov** [goabstract/abstract-sdk#322]
I'm saving a sketch file locally using [raw ](https://sdk.goabstract.com/docs/abstract-api/#export-a-file)API from abstract sdk, but since today it started failing with the following error. I also checked the access tokens and tried with new one, but it is still the same.

```
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'MultiError',
  errors: {
    cli: Error: spawn UNKNOWN
        at ChildProcess.spawn (internal/child_process.js:407:11)
        at spawn (child_process.js:548:9)
```

```
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
      errno: 'UNKNOWN',
      code: 'UNKNOWN',
      syscall: 'spawn'
    },
    api: Error: Received status "400", expected 2XX
```

![image](https://user-images.githubusercontent.com/1182001/100746042-daba3e00-33e8-11eb-8cc2-259e6626cb85.png)

**Comment by tommoor** [comment]
Thanks for filing, we're investigating this internally now

**Comment by joesteele** [comment]
This should be working again. Let us know if it's still failing for you.

**Comment by dkamburov** [comment]
Thanks! It's working now.
