### ISSUE TITLE
v8 'List all files' API throws NotFoundError

### ISSUE THREAD

**Issue by jzempel** [goabstract/abstract-sdk#323]
Is the [`files.list`](https://sdk.goabstract.com/docs/abstract-api/#list-all-files) API expected to work without changes in v8? I don't see any related breaking changes in the [changelog](https://github.com/goabstract/abstract-sdk/blob/master/CHANGELOG.md). I'm attempting to [upgrade](https://github.com/zendeskgarden/website/pull/218) and seeing the following errors at the moment `files.list` is invoked with configuration:

<img width="465" alt="Screen Shot 2020-12-05 at 12 54 28 PM" src="https://user-images.githubusercontent.com/143773/101265211-9f29b780-36f9-11eb-9cf1-cc1bfdd44f32.png">

The same call works as expected with v7.0.1.

**Comment by tommoor** [comment]
Are you passing a `sha` parameter? If not try passing `sha=latest` in the parameters

**Comment by jzempel** [comment]
Yes, we are passing a valid SHA that works in v7.

https://github.com/zendeskgarden/website/blob/f82df3f91622ea9545902d2c9ff2ecbc978468c5/plugins/gatsby-source-abstract/gatsby-node.js#L37-L45

**Comment by tommoor** [comment]
Thanks, on our side it looks like the `sha` was likely unused in v7: https://github.com/goabstract/abstract-sdk/compare/v7.0.1...v8.1.0#diff-9563835050a3ed8167dece5087403b921a96405a477a0cb29019648f3d395eb9L58

So it could be that it's incorrect? Give "latest" a try as the value just to see if that works or the error persists and we can investigate further from there

**Comment by jzempel** [comment]
Ha - that did the trick. Thanks.
