### ISSUE TITLE
Unable to make API requests through proxy

### ISSUE THREAD

**Issue by JSMike** [goabstract/abstract-sdk#328]
Currently there's no way to configure a proxy for API requests.

I would suggest allowing users to optionally pass a [http-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) when creating a new Abstract Client

```
const Abstract = require('abstract-sdk');
const HttpsProxyAgent = require('https-proxy-agent');

const proxyAgent = new HttpsProxyAgent('http://my-https-proxy:8080');
const client = new Abstract.Client({
  accessToken: process.env.ABSTRACT_KEY,
  transportMode: ['api'],
  proxyAgent: proxyAgent
});
```

Add optional proxyAgent to Client and update the agent to the [fetch options](https://github.com/goabstract/abstract-sdk/blob/master/src/endpoints/Endpoint.js#L118) 

```
fetchOptions.agent = Client.proxyAgent;
``` 

Solution based on [this blog post](https://www.scrapingbee.com/blog/proxy-node-fetch/)

**Comment by tommoor** [comment]
If you'd like to try a pre-release version of the SDK with this feature, see `v8.1.2-0`
