### ISSUE TITLE
API: preview.info

### ISSUE THREAD

**Issue by igorsheg-wix** [goabstract/abstract-sdk#40]
Hey, 

I'm trying to get the preview to work - to get an png of a layer.

I'm using `preview.info`

Getting `https://previews.goabstract.com/projects/eda68300-e1d0-11e8-8133-0b70a3eae7f0/commits/51bf03f17a6234d6f703b86d2309fe5ae4a28034/files/D06C3330-664C-4F89-B8E6-AC27B93AF4DC/layers/4DF3A97D-3F66-48A1-9459-B42B3154391C`

then when i try to access it I get `{"error":"forbidden"}`

maybe the documentation is unclear or I got something wrong.

Thanks in advance!

**Comment by tommoor** [comment]
Hey Igor, short answer is – use `previews.raw` to get the data and save it somewhere. The previews service requires authentication with a token which would have to be saved with the URL. 

We're looking into how this can be improved (perhaps with a previews specific short-lived token) as we realize it's not as developer friendly as it should be.

**Comment by tommoor** [comment]
> you should also be able to pass sha: "latest" in the descriptor

Ah, of course 🙈 – should have mentioned that too.

**Comment by igorsheg-wix** [comment]
@tommoor @amccloud Thanks guys ;)
