### ISSUE TITLE
API: activities.list

### ISSUE THREAD

**Issue by igorsheg-wix** [goabstract/abstract-sdk#43]
Hey, I'm currently getting `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'list' of undefined` on `activities.list`. 

is this part of the API not implemented yet? or am I doing something wrong?

**Comment by tommoor** [comment]
It looks like we haven't published that work to NPM – @amccloud any reason we shouldn't?

**Comment by amccloud** [comment]
@igorsheg-wix just published v0.5.0 with a newly added changelog:  https://github.com/goabstract/abstract-sdk/blob/master/CHANGELOG.md
