### ISSUE TITLE
Add users endpoints to API transport

### ISSUE THREAD

**Issue by tommoor** [goabstract/abstract-sdk#55]
We're currently missing endpoints for `users.list` and `users.info` – as we don't send this information back with branch data (https://github.com/goabstract/abstract-sdk/issues/45) it's important that it can be loaded separately.

**Comment by bitpshr** [comment]
Would we use the `/scim/v2/Users` endpoints for this, or would we add new endpoints to the users controller exposed at `/users`?

**Comment by tommoor** [comment]
Nothing related to SCIM here – thanks for asking for clarification. This is an interesting one now that I remember our API in more detail, right now we have endpoints for "memberships", but nothing for users, eg:

`GET /organizations/:organization_id/memberships`
`GET /projects/:project_id/memberships`

These return membership objects that include a nested `user`:

![image](https://user-images.githubusercontent.com/380914/50188763-8be86c00-02d7-11e9-8a70-275c957c56fd.png)

I'm not entirely sure how we should represent this in the SDK now and very open to thoughts…

I do think it would be worth adding a `GET /users/:id` too for individual user lookup though.

**Comment by bitpshr** [comment]
What if `users.list` took either an `OrganizationDescriptor` or a `ProjectDescriptor`, and depending on which one is passed, it calls out to either `/organizations/:organization_id/memberships` or `/projects/:project_id/memberships`, respectively. It could map the resulting membership list and only return users.

Alternatively, I'd be fine with adding a new `GET /users` endpoint too. I think we'd just find the organization based on an `organization_id` URL parameter, then return its `users`.
