### ISSUE TITLE
Change documentation deployment to not happen on master

### ISSUE THREAD

**Issue by tommoor** [goabstract/abstract-sdk#62]
We often have work sat on master that hasn't yet been published to NPM as we're working towards a release. As it stands right now documentation updates related to this work get auto-deployed with master.

We've discussed:

- **Deploying docs when a release is tagged.** This one is great in that it requires no thinking but prevents us from updating docs outside of the release cycle.
- **Deploying docs by pushing to a branch.** This requires manual deployment but we can do so at any time.

Currently swaying towards the branch approach.

**Comment by amccloud** [comment]
👍 tags + branch approach would be nice. I just patched the documentation for a typo and it would have been tedious to bump a release for that.

We can keep the docs in sync with the head of a branch and merge in tags when they are created or manually merge for typos and such
