### ISSUE TITLE
Add shares.create API endpoint

### ISSUE THREAD

**Issue by bitpshr** [goabstract/abstract-sdk#69]
We should add a new endpoint to the API transport to support the creation of share links. The required API route for this already exists, so it should just be a matter of adding this call to the SDK.

**Comment by amccloud** [comment]
I ended up building this out trying to fix the flowtypes for `share.descriptor` and our ShareButton https://github.com/goabstract/abstract-sdk/compare/shares-create

If you are wondering about the `.bind(this)` it's because I ran into

Still needs docs and to be tested
