### ISSUE TITLE
Add assets.info, assets.list, and assets.raw CLI endpoints

### ISSUE THREAD

**Issue by bitpshr** [goabstract/abstract-sdk#72]
We should add new endpoints to the CLI transport to support listing all assets, getting one asset, and getting one asset's raw data. This will involve new CLI commands to support all operations.

**Comment by bitpshr** [comment]
I checked in with @jleldridge about adding new functionality to the CLI to handle these new SDK methods, such as getting all assets for a layer. He mentioned that this would ultimately boil down to an internal API request, similarly to what's done for `collections`.

Since the CLI would call out to the API anyways, do we even want to include `assets` methods in the CLI transport? This is pretty much the same situation @rickharris pointed out about `collections` at https://github.com/goabstract/abstract-sdk/pull/77/files#r250498743.

cc @amccloud @tommoor @rickharris

**Comment by tommoor** [comment]
Maybe the pragmatic solution is to build out the API transport first and come back to the CLI as a potential followup layer…

I think the CLI methods that we are likely to want in the SDK are those associated with generating assets – just so we can complete the goal of eventually having full coverage, but for then near-term goal of public usefulness the API makes most sense.

**Comment by bitpshr** [comment]
Thanks @tommoor. I think it makes sense to close this issue since even when we add `assets` functionality to the CLI transport, it sounds like we'd focus on generation, not functionality that only calls out the API like `info` and `list`.

I created https://github.com/goabstract/abstract-sdk/issues/84 to track adding generation methods.
