### ISSUE TITLE
Add files.raw CLI and API endpoints

### ISSUE THREAD

**Issue by bitpshr** [goabstract/abstract-sdk#73]
We should add a new endpoint to both the CLI transport and the API transport to support retrieving the raw data for a single file. This will involve a new API and CLI command to support each respective operation.

**Comment by bitpshr** [comment]
Closing until we fully flesh out API vs. CLI transport offerings.

**Comment by Zahlii** [comment]
Any ETA on this feature/discussion? For me, supporting raw file downloads is crucial for a successful automation of our current workflow.

**Comment by tommoor** [comment]
@bitpshr could you speak to why this was closed, seems like we could go ahead with the API versions of these at least?
