### ISSUE TITLE
Remove pageId from LayerDescriptor

### ISSUE THREAD

**Issue by amccloud** [goabstract/abstract-sdk#76]
Would be nice to remove `pageId` from `LayerDescriptor`

- [x] [Layer routes](https://github.com/goabstract/ui/pull/204/files#r246593467)
- [x] [Share links](https://github.com/goabstract/projects/pull/1507)
- [x] [comments.create](https://github.com/goabstract/abstract-sdk/pull/106)
- [x] [LayerDescriptor](https://github.com/goabstract/abstract-sdk/pull/106)

**Comment by bitpshr** [comment]
This was resolved by @amccloud in #106.
