### ISSUE TITLE
Implement a request cache

### ISSUE THREAD

**Issue by bitpshr** [goabstract/abstract-sdk#87]
We should cache requests where possible to improve perceived performance and to reduce load on our servers.

**Comment by amccloud** [comment]
Another place that could benefit from a cache https://github.com/goabstract/abstract-sdk/blob/master/src/AbstractAPI/index.js#L512

An identity map from descriptor@sha to objects might be a good way to start. I believe any object returned from a descriptor with a sha can be cached indefinitely as long as we have the entire object

For descriptors without sha `branch.head` may be an option

**Comment by amccloud** [comment]
Can possibly use something like https://github.com/paularmstrong/normalizr to ingest the response into a cache
