### ISSUE TITLE
previews: Add method to retrieve preview url

### ISSUE THREAD

**Issue by tommoor** [goabstract/abstract-sdk#92]
`previews.raw` is great if you want a copy of the file to save in your own datastore, but it's an awkward interface for displaying in the web browser.

Lets add an additional method to grab a data-uri for the image using the `bufferToUrl` helper we have internally. This issue was triggered by confusion from a customer attempting to use the `webUrl` method…

**Comment by ServusJon** [comment]
Is there a method to get the url to artboard for the browser? So you can use the Inspect functionality?

**Comment by tommoor** [comment]
That would be `previews.webUrl` which links to the artboard in our web app.

**Comment by ServusJon** [comment]
We tried that link but it always showed us "forbidden" .
Also, is there a generalized link to an artboard that isn't connected to a commit but to the most recent version of it?

**Comment by amccloud** [comment]
@ServusJon whoops! `webUrl` is actually pointing to the preview image file but that requires authentication. 

PR incoming to get direct access to the image and to update webUrl. In the meantime you could try replacing `previews.goabstract.com` with `app.goabstract.com` in the current webUrl

**Comment by ServusJon** [comment]
Cool! That will work!

**Comment by amccloud** [comment]
`previews.url` was added in `v0.7.5` https://sdk.goabstract.com/docs/abstract-api/#retrieve-a-preview-image-url
