### ISSUE TITLE
Not found error on preview export

### ISSUE THREAD

**Issue by ServusJon** [goabstract/abstract-sdk#93]
I created a loop to save images of all my artboards on all pages. For some images I get a not found error. I looked inside Sketch but I couldn't identify why some artboards work and some won't.

`(node:43291) UnhandledPromiseRejectionWarning: NotFoundError: Not found.
    at throwAPIError (/Users/Jonathan.Arnold/Desktop/_spikeweek_test/node_modules/abstract-sdk/lib/errors.js:143:13)
    at AbstractAPI.fetch (/Users/Jonathan.Arnold/Desktop/_spikeweek_test/node_modules/abstract-sdk/lib/AbstractAPI/index.js:509:39)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:43291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:43291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

@tommoor my team at Freeletics want to use that feature for a very quick project that has to be completed till friday. I would really appreciate if you can look into that and provide some insights.

Thank you :-)

**Comment by tommoor** [comment]
My guess would be that you're attempting to load the preview at a commit `sha` where it was not edited. We only store previews when the artboard changed, so you'll probably be looking for the `lastChangedAtSha` 

https://github.com/goabstract/abstract-sdk/blob/444ed0e93f52f7441b5101908f077dc9fddf52cb/src/types.js#L781

**Comment by ServusJon** [comment]
Thanks for this fast reply. I will check if that works! 
Also, for some image we got a "too many requests" error. Our code will run in the background, so speed is not really critical. Do you have a recommendation how fast we can send our requests and not run into that error? @tommoor

**Comment by tommoor** [comment]
> Do you have a recommendation how fast we can send our requests and not run into that error?

I believe our current limit is 60 requests per minute during this ramp up period. We hope to be able to raise this though as the API performance characteristics are better known 😄

**Comment by ServusJon** [comment]
@tommoor is there a way to get the preview images in @2x?

**Comment by tommoor** [comment]
Not yet 😢 – we're working on the infrastructure to support this.
